language: php

php:
  - 5.2
  - 5.3
  - 5.4

  - 5.3.2
  - 5.3.8

env:
  - DB=mysql

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi"
  - sh createTempDirectory.sh
  - chmod -R 777 ./app/tmp
  - cp app/Config/core.php.default app/Config/core.php
  - cp app/Config/config.php.default app/Config/config.php
  - echo "<?php
    class DATABASE_CONFIG {
    public \$default = array(
      'datasource' => 'Database/Mysql',
      'host' => '0.0.0.0',
      'login' => 'travis',
      'persistent' => false,
      'host' => '',
      'login' => '',
      'password' => '',
      'database' => 'cakephp_test',
      'prefix' => ''
    );
    public \$test = array(
      'datasource' => 'Database/Mysql',
      'host' => '0.0.0.0',
      'login' => 'travis',
      'persistent' => false,
      'host' => '',
      'login' => '',
      'password' => '',
      'database' => 'cakephp_test',
      'prefix' => ''
    );
    }" > app/Config/database.php
#  - sh app/Console/cake schema create WikiPages
#  - sh app/Console/cake schema create WikiElements
#  - sh app/Console/cake schema create WikiImages

script: ./app/Console/cake testsuite app Model/WikiPage

#notifications:
# email: false
